### ISSUE TITLE
Consider kustomize components to differentiate http-pulsar-poller instances

### ISSUE THREAD

**Issue by haphut** [tvv-lippu-ja-maksujarjestelma-oy/waltti-apc#204]

**Comment by jahpola** [comment]
Kustomize components are on top of base -> won't work. If there is a base app 1 we can't create two base apps.

**Comment by jahpola** [comment]
Tested with single kustomize +overlays - this creates complicated kustomize setup and Argocd shows them as a single app. May be the approach should be another? Two different apps using a base.
