### ISSUE TITLE
Make auto-merged Dependabot PRs trigger Docker login and push

### ISSUE THREAD

**Issue by haphut** [tvv-lippu-ja-maksujarjestelma-oy/waltti-apc#264]
This seems to be the case: "Doesn't work if pushed by bot, like github-actions." https://github.com/orgs/community/discussions/25812

Compare: https://github.com/tvv-lippu-ja-maksujarjestelma-oy/http-pulsar-poller/commits/main and https://hub.docker.com/r/tvvlmj/http-pulsar-poller/tags

More issues on the topic: 
- https://github.com/dependabot/fetch-metadata/issues/111
- https://github.com/dependabot/fetch-metadata/pull/162

Solutions:
1. Use a GitHub App such as Mergify (free for open source).
1. Use a Personal Access Token (PAT).
1. Create our own GitHub App and possibly host it somewhere.

Solution 1 depends on the service remaining free for open source and not going bankrupt.

Solution 2 depends on creating a person-dependent token and probably putting it into the waltti org or every repo separately. Who should create the PAT and promise to never destroy it? Also need to ask for help from Waltti personnel to put it into the org.

Solution 3 sounds like too much work.

**Comment by jahpola** [comment]
Agree, as 2 is disaster in long term, And 3 is too much work.
