### ISSUE TITLE
Remove pid from pino log messages

### ISSUE THREAD

**Issue by jahpola** [tvv-lippu-ja-maksujarjestelma-oy/waltti-apc#300]
https://github.com/pinojs/pino/blob/master/docs/api.md#options 

base: { } removes both pid and hostname. Hostname should stay

**Comment by jahpola** [comment]
Using following code snippet works for removing pid:
```
redact: {
          paths: [ "pid"],
          remove: true
        }
```

**Comment by haphut** [comment]
Well done! Now in `main` in http-pulsar-poller. Should be incorporated in all repos.
