### ISSUE TITLE
E2E testing framework

### ISSUE THREAD

**Issue by jahpola** [tvv-lippu-ja-maksujarjestelma-oy/waltti-apc#302]
1. How to test?
2. How to integrate testing into CI/CD?

**Comment by jahpola** [comment]
An external service that sends and reads.

**Comment by haphut** [comment]
- mosquitto mqtt broker docker to replace cloudamqp
- python http server to serve static test files, one for each gtfs realtime city, one for vehicle registry
  - `python3 -m http.server -d served 8000` serves directory `served`. 
  - This switches between the numerically ordered files in directory:
      ```sh
      #!/bin/bash

      set -Eeuo pipefail

      for filename in source/*; do
        echo 1>&2 "Set target to ${filename}"
        ln -f -s "${filename}" 'served/target'
        sleep 3
      done
      ```
  - `curl 'http://localhost:8000/target'` should ask for file `target` but has some bug

**Comment by haphut** [comment]
Alternative:

- one typescript service
- sending loop
  - http server and mqtt client (producer)
  - static json files in data directory
  - mqtt client spews the apc json files into topics
  - http server reads json and turns it into GTFS Realtime VP protobuf data
  - http server also serves vehicle registry output
  - coordination file with contents similar to this:
    - scenario: bus-leaves
    - messages:
      - path: http/vehicle-registry/all-vehicles.json
      - path: http/jyvaskyla/no-service.json
      - path: http/kuopio/en-route.json
      - path: mqtt/acme-vendor/door-1-in-2.json
      - path: mqtt/counting-corporation/door-2-out-1.json
      - path: mqtt/first-stop.json
        waitAfterForSeconds_OPTIONAL_AS_DEFAULT_IN_ENV_VAR_0.1: 0.5
      - path: http/kuopio/left-stop.json
      - path: http/jyvaskyla/bus-on-first-stop.json
- receiving loop
  - mqtt client (subscriber)
  - expected json results in data directory
  - compares received data with data directory contents, in order
  - coordination file:
    - messages:
      - path: mqtt/apc/authority-221/door-1-in-2.json
      - path: mqtt/anonymized-apc/authority-221/trip-y-empty.json
- how to do several scenarios?
  - no clean-up in between, just run message lists in order with a wait in between
    - easy to write but tests affect each other
  - in between each scenario: stop all k8s services, empty all pulsar topics, start k8s services again
    - how hard is this?
    - tests independent
- should alternative k8s manifests be in the e2e repo? can we just partly override dev manifests, e.g. URLs?
- note: naming files like `00001-...` has the problem that most changes require renaming many files
- for linting, we could add json schemas and schema checking in the e2e repo.

**Comment by jahpola** [comment]
1. Stopping Kubernetes service is rather easy just scale down to 0.
2. Emptying pulsar topics is the harder part, would most likely need pulsarctl/pulsaradmin cli tools to wipe them clean.
3. Overriding dev -> another kustomize overlay, might be easier to create "testing" namespace and deploy them all into into (feature branch testing)

**Comment by jahpola** [comment]
I see two choices:
1. Keep everything as is then monitor the application(s) via GCP monitoring tools
2. Create our own "framework" for testing the thing. Could be also "faked" via testcontainer mqtt+pulsar containers. Problem.... the majority of testcontainer mqtt+pulsar is written in Java.
