### ISSUE TITLE
Log levels are missing in GCP log explorer

### ISSUE THREAD

**Issue by jahpola** [tvv-lippu-ja-maksujarjestelma-oy/waltti-apc#336]
Log levels are missing or wrong in log explorer. Log explorer can't use our log level numbers. See https://github.com/pinojs/pino/issues/726 for more details

**Comment by jahpola** [comment]
From Pino docs:
_Google Cloud Logging uses severity levels instead of log levels. As a result, all logs may show as INFO level logs while completely ignoring the level set in the pino log. Google Cloud Logging also prefers that log data is present inside a message key instead of the default msg key that Pino uses. Use a technique similar to the one below to retain log levels in Google Cloud Logging_

**Comment by haphut** [comment]
Fixed in gcpLogging.ts in several repos.
