### ISSUE TITLE
Data sharing: Operator data, Open Data

### ISSUE THREAD

**Issue by samijuhani** [tvv-lippu-ja-maksujarjestelma-oy/waltti-apc#51]
Discussions held with HSL about data sharing to operators as open data, etc. To be specified.

**Comment by haphut** [comment]
It should be straightforward to publish an archive of anonymized APC data that has already been published over GTFS Realtime. Not in scope for the pilot, though.

It's important to avoid anonymizing twice, once for public real-time APIs and once for public archives, as then comparing the datasets might reveal individuals.

**Comment by haphut** [comment]
This is out of scope for this system. It makes sense to add this requirement into Waltti datalake or something similar. With the emphasis: "It's important to avoid anonymizing twice, once for public real-time APIs and once for public archives, as then comparing the datasets might reveal individuals."
